server:
  port: 8080

spring:
  profiles:
    active: dev
  liquibase:
    enabled: true
    change-log: classpath:db/migration/db.changelog-master.yaml
    parameters:
      BANK_ADMIN_PASSWORD: ${BANK_ADMIN_PASSWORD}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

card:
  bin: "400000"
  retry-limit: 100
  encryption:
    secret: ${CARD_ENCRYPTION_SECRET}
  hash:
    secret: ${CARD_HASH_SECRET}

jwt:
  secret: ${BANK_JWT_SECRET}
  access-expiration: 86400000 # 1 day
  refresh-expiration: 2592000000 # 30 days