spring:
  datasource:
    url: jdbc:h2:mem:bank_cards;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

card:
  encryption:
    secret: "1234567890123456"
  hash:
    secret: "1234567890123456"

jwt:
  secret: "dGhpcyBpcyBhIHZlcnkgbG9uZyBzZWNyZXQga2V5IGZvciBKV1QgdG9rZW4gc2lnbmluZyE="
  access-expiration: 1800000
  refresh-expiration: 604800000